# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - PawelLipski
    target-branch: develop
    # TODO (#771): remove this pin once sphinx-rtd-theme 1.2.0 is released
    ignore:
      - dependency-name: "sphinx"
