version: '3'
services:
  deb-ppa-test-install:
    image: gitmachete/ci-deb-ppa-install:${UBUNTU_VERSION}
    build:
      context: build-context
      dockerfile: ../Dockerfile # relative to build-context
      args:
        launchpad_username: ${LAUNCHPAD_USERNAME}
        ubuntu_version: ${UBUNTU_VERSION}
