version: '3'
services:
  deb-ppa-upload:
    image: gitmachete/ci-deb-ppa-upload:${DIRECTORY_HASH:-unspecified}
    build:
      context: build-context
      dockerfile: ../Dockerfile # relative to build-context
      args:
        - user_id=${USER_ID:-0}
        - group_id=${GROUP_ID:-0}
    volumes:
      # Host path is relative to current directory, not build-context
      - ./../..:/home/ci-user/git-machete
    environment:
      - TARGET_DISTRO_NAME
      - TARGET_DISTRO_NUMBER
    env_file:
      - gpg-ssh.env
