version: '3'
services:
  nixpkgs-pr:
    image: gitmachete/ci-nixpkgs-pr:${DIRECTORY_HASH:-unspecified}
    build:
      context: build-context
      dockerfile: ../Dockerfile # relative to build-context
    tty: true
    environment:
      - DO_PUSH
      - GITHUB_TOKEN
      - PYPI_HOST
      - VERSION
