version: '3'
services:
  ppa-upload:
    image: virtuslab/git-machete-ci-ppa-upload:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: upload.Dockerfile
      args:
        - user_id=${USER_ID:-0}
        - group_id=${GROUP_ID:-0}
    volumes:
      - ${PWD}/../..:/home/ci-user/git-machete
    env_file:
      - upload-vars.env
  ppa-test-install:
    build:
      context: .
      dockerfile: test-install.Dockerfile
